### ISSUE TITLE
Use gdb to debug a sketch

### ISSUE THREAD

**Issue by nkolban** [me-no-dev/RasPiArduino#11]
In the Pi environment we have access to the gdb source code debugger which can be run locally or remotely.  It would seem to be possible to run gdbserver on the Pi and gdb on the PC to attach a remote debugger to the Pi to debug the execution of the sketch.  Quite how we will accomplish this is not yet known ... this issue is to track progress on that possibility.

**Comment by nkolban** [comment]
A first pass at implementation has been performed.  This implementation adds a new option in the Tools menu called `Enable gdb`.  The option has two menu choices which are:

* `Enabled`
* `Disabled` (Default)

When enabled is selected, the code is compiled with an extra compilation option ... namely the `-g` flag.  This causes the code to be compiled with additional symbolic information included within it that will allow the GDB debugger (and variants) to be used to source code debug the Sketch.

Here is an example of the new tools menu:

<img width="261" alt="2016-02-05_20-21-41" src="https://cloud.githubusercontent.com/assets/3421732/12864041/20923ea6-cc46-11e5-8ce3-5bc4973dce9f.png">

For more information on compiling with debugging enabled, see:
* [GDB: The GNU Project Debugger](https://www.gnu.org/software/gdb/)
* [Compiling for debugging](https://sourceware.org/gdb/current/onlinedocs/gdb/Compilation.html#Compilation)

**Comment by nkolban** [comment]
Initial testing seems to show something not working as expected.  When I place a breakpoint in the code in loop and run the sketch, sure enough we break ... but when I "next", it is almost like a second thread has started and we are toggling between TWO threads of the solution.  I need to consult with @me-no-dev to demonstrate the issue and see if he has any notions of what might be happening.

**Comment by me-no-dev** [comment]
try with removing the optimization (-O3 currently). Maybe stuff get's lost there.

**Comment by nkolban** [comment]
After removal of the -O3 compilation optimization flags as suggested by @me-no-dev, the gdb debugging now seems to work correctly.  More testing is obviously required but so far no issues.
