### ISSUE TITLE
Missing definition for pthread_setname_np

### ISSUE THREAD

**Issue by nkolban** [me-no-dev/RasPiArduino#31]
When we build a sketch, there is now a warning that pthread_setname_np() is undefined.  This can be found in wiring_thread.c.   Checking the man page here, http://man7.org/linux/man-pages/man3/pthread_setname_np.3.html, it seems that this requires the definition of the symbol _GNU_SOURCE.  This issues requests a resolution for a clean compile by either adding the symbol definition as needed or else removing / replacing the function call that is creating the undefined.

**Comment by me-no-dev** [comment]
I have added the definition but you have not updated your platform.txt
