### ISSUE TITLE
Recipe for disabling getty from serial port ...

### ISSUE THREAD

**Issue by nkolban** [me-no-dev/RasPiArduino#37]
A default instance of Raspbian has getty running against the serial port.  Chances are we don't want to do this if we are using the serial port for the Arduino interfacing.  This then says that we want to disable the start up of the getty.   One way to do this is to run:

```
$ sudo systemctl disable serial-getty@ttyAMA0
```

The current recipe in our README has us edit a boot file.  I am wondering if that is needed, can we just use systemctl and which would be a preferred method?

**Comment by me-no-dev** [comment]
the one in boot is for the boot process, the one you explain is once the kernel has booted.
