### ISSUE TITLE
Use EthernetServer with Pi network interface

### ISSUE THREAD

**Issue by moelski** [me-no-dev/RasPiArduino#56]
Hi !

I tried to compile the webserver example which works fine. But after looking into the libs I saw that it is all based on the W5100 chip - so the standard ethernet breakout for the arduino. 
The Pi has embedded network support so can you give some advice how to use the EthernetServer class with the Pi network interface?

Dominik

**Comment by me-no-dev** [comment]
Sure :)
The PI uses the Bridge classes to provide networking, file access and more.
You can find it [here](https://github.com/me-no-dev/RasPiArduino/tree/master/libraries/Bridge/src)

**Comment by moelski** [comment]
Hi !

Shame on me ... 
Will give it a try. Thx for your help.

**Comment by moelski** [comment]
Hi again, 
you can Close this issue. The Bridge Classes work great.

**Comment by me-no-dev** [comment]
good :)
