### ISSUE TITLE
How to cast to String? 

### ISSUE THREAD

**Issue by moelski** [me-no-dev/RasPiArduino#57]
Hi !

Just try to get the ESP8266WebServer running with RasPiArduino. It works but there are some small Problems. One is the casting of int to string for example. 
This is the some Code from the webserver: 
`void PiWebServer::_prepareHeader(String& response, int code, const char* content_type, size_t contentLength) {
    response = "HTTP/1."+String(_currentVersion)+" ";
    response += String(code);
...}`
The casting of _currentVersion (which is uint8_t) results in an unreadable character. 

I found a solution which works: 
`  char buffer[256];
  sprintf(buffer, "%d", x);`

But maybe there is a more elegant and easier solution?

Dominik

**Comment by me-no-dev** [comment]
this sounds rather like bug in String

**Comment by moelski** [comment]
Could you have a short look if this issue can be fixed ?

**Comment by moelski** [comment]
Hi !
I have enhanced the WString class and now all string related stuff is working. 
I have also make a "PiWebServer" class based on the ESP8266 stuff. 
Would love to make a pull request - but I can´t ... 

So How can I contribute to this project ?

**Comment by me-no-dev** [comment]
you fork the repository, add your changes there and make a PR to this repo :)

**Comment by moelski** [comment]
Hi !

I think this topic can be closed. The PR #58 from me fixes all my issues.
